server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taskapp
    password: saigon
    username: root
  thymeleaf:
    cache: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  servlet:
    multipart:
      max-request-size: 2MB
      max-file-size: 2MB
      enabled: true
